#!/bin/sh
# Copyright (C) 2026 David Nichols
# SPDX-License-Identifier: MIT
set -eu
export LC_ALL=C.UTF-8
unset QORE_MODULE_DIR QORE_MODULE_DIR_ONLY QORE_INCLUDE_DIR LD_LIBRARY_PATH LD_PRELOAD PYTHONPATH PYTHONHOME
export QORE_MODULE_DIR=$(/usr/bin/qore --module-path)
export QORE_MODULE_DIR_ONLY=1
cp test/proj-python.qtest "$AUTOPKGTEST_TMP/"
cd "$AUTOPKGTEST_TMP"
timeout 180 /usr/bin/qore proj-python.qtest -v
timeout 180 /usr/bin/qore -DPythonFirst proj-python.qtest -v
